### PR TITLE
Adding images for the Hack Club finder

### PR DESCRIPTION
**Pull request by ajyu124**
Added a bunch of missing school images. Hope this is helpful! :)

### CODE REVIEW

**Comment by ifvictr** [comment]
@Zypker124 Thanks, this is awesome! Did you make sure to run the script on the images? If not, just run `gulp compress:schools`.

**Comment by ajyu124** [comment]
Where do you run the gulp compress:schools on?

**Comment by ifvictr** [comment]
Just run the command. It will automatically iterate through all the images in `assets/images/school` and perform the necessary operations on them.

**Comment by ajyu124** [comment]
I'm not familiar with Github tbh, so where do you run the command?

**Comment by ifvictr** [comment]
Clone this repo to your local environment, run `npm install` to install everything needed, and then run the aforementioned command.

**Comment by lachlanjc** [comment]
@ifvictr I resized all of them to 500 and ran them through guetzli. I can't modify this PR, but here's the school folder with @Zypker124's additions.
[school.zip](https://github.com/hackclub/finder/files/1795524/school.zip)

**Comment by ifvictr** [comment]
@lachlanjc Thanks. The processed images have been added in https://github.com/hackclub/finder/commit/f540790fddc4bc8009165e73d9981153d48b4c8e.

@Zypker124 Thanks for the contribution! I couldn't seem to modify your PR, so I just pushed it in a separate commit (https://github.com/hackclub/finder/commit/f540790fddc4bc8009165e73d9981153d48b4c8e).

**Pull request closed without merging**
